# GitHub Actions 工作流程的名稱
name: Deploy to Firebase Hosting

# 觸發條件：當有程式碼被 push 到 main 分支時
on:
  push:
    branches:
      - main

# 工作內容
jobs:
  build_and_deploy:
    # 運行的虛擬機環境
    runs-on: ubuntu-latest
    
    # 工作的步驟
    steps:
      # 步驟 1: 從 GitHub 下載您的專案程式碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步驟 2: 設定 pnpm 套件管理器
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      # 步驟 3: 設定 Node.js 環境 (並啟用 pnpm 快取)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 步驟 4: 安裝專案所有依賴套件 (使用最穩定的 frozen-lockfile)
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # 步驟 5: 打包建置 Next.js 專案
      - name: Build Project
        run: pnpm build

      # 步驟 6: 部署到 Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: babix-web-app